= Cheatsheets

[[SingleMessageResult]]
== SingleMessageResult

++++
 Describes result for a single device ID. GCM returns such result for each device ID the notification has been sent to.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[error]]`error`|`link:enums.html#SingleMessageErrorType[SingleMessageErrorType]`|
+++
Error type
+++
|[[messageId]]`messageId`|`String`|
+++
Message ID that Google has assigned to this message
+++
|[[registrationId]]`registrationId`|`String`|
+++
New registration ID that should be used in the future instead of the original one used in this request.
 See <a href="https://developers.google.com/cloud-messaging/registration#canonical-ids">Canonical IDs</a>
+++
|[[success]]`success`|`Boolean`|
+++
Whether the notification has been successfully queued for delivery on that device.
 It doesn't mean the notification has really been delivered.
 Also reply with canonical ID is considered successful.
+++
|===

[[GcmServiceConfig]]
== GcmServiceConfig

++++
 @author Michal Boska
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[address]]`address`|`String`|
+++
Eventbus address this service will listen on. Only makes sense when using this service in a standalone mode (as a separately-deployed verticle).
+++
|[[apiKey]]`apiKey`|`String`|
+++
API key to authenticate with against GCM HTTP servers. See <a href="https://developers.google.com/cloud-messaging/http#auth">GCM documentation</a>.
 Required parameter.
+++
|[[backoffMaxSeconds]]`backoffMaxSeconds`|`Number (Integer)`|
+++
Maximum number of (total) seconds this service can take in retrying notifications with recoverable errors.
 After this time, it will return the current result, what it managed to sent successfully so far.

 If both this and <code>backoffRetries</code> are null, retry mechanism is not applied.
+++
|[[backoffRetries]]`backoffRetries`|`Number (Integer)`|
+++
Maximum number of attempts the GCM service can make to retry a recoverable error received from the GCM server.
 This applies to global errors (such as recoverable HTTP-500) as well as recoverable errors per device-id.

 If both this and <code>backoffMaxSeconds</code> are null, retry mechanism is not applied.
+++
|[[localOnly]]`localOnly`|`Boolean`|
+++
Whether this service should register a local-only eventbus handler. If true, the eventbus registration will not be propagated accross the Vert.x cluster
 and messages sent from another cluster nodes will not be delivered to this service.
 Only makes sense when using this service in a standalone mode (as a separately-deployed verticle).
+++
|[[maxSecondsToLeave]]`maxSecondsToLeave`|`Number (Integer)`|
+++
Maximum number of seconds that can be sent as notification's <code>ttlSeconds</code> parameter
+++
|[[registrationIdsLimit]]`registrationIdsLimit`|`Number (Integer)`|
+++
Maximum number of registration IDs sent in a single notification. If a notification contains more IDs than this, an exception is thrown.
+++
|===

[[GcmResponse]]
== GcmResponse

++++
 @author Michal Boska
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[canonicalIdCount]]`canonicalIdCount`|`Number (Integer)`|
+++
A total number of canonical IDs in this response.
 See <a href="https://developers.google.com/cloud-messaging/registration#canonical-ids">Canonical IDs</a>
+++
|[[canonicalIdsMap]]`canonicalIdsMap`|`String`|
+++
A convenience method to collect all registration IDs, that have their newer versions available (for the same device) along with those newer IDs.
 The sender should update its database to use the newer registration ID for the same device in the future.
+++
|[[deviceIdsToRetry]]`deviceIdsToRetry`|`Array of String`|
+++
Get a set of device IDs for which a recoverable error has been encountered and it makes sense to retry the operation
 after a certain delay
+++
|[[deviceResults]]`deviceResults`|`link:dataobjects.html#SingleMessageResult[SingleMessageResult]`|
+++
A map of (Device ID -> SingleMessageResult) pairs
+++
|[[failureCount]]`failureCount`|`Number (Integer)`|
+++
A total number of failures (counted per requested Device ID)
+++
|[[invalidRegistrationIds]]`invalidRegistrationIds`|`Array of String`|
+++
A convenience method to collect all registration IDs, that were rejected by GCM, because they are invalid.
 This list does not contain registration IDs that failed due to other reasons than being invalid (for example due to technical difficulties at GCM).
 <p>
 IDs returned by this method should presumably be removed from the sender's database.
+++
|[[multicastId]]`multicastId`|`Number (Long)`|
+++
Multicast ID assigned by Google
+++
|[[retryAfterSeconds]]`retryAfterSeconds`|`Number (Integer)`|
+++
In case of recoverable error, GCM server may sent a retry-after header. Undocumented by Google, not really working yet
+++
|[[successCount]]`successCount`|`Number (Integer)`|
+++
Total number of device IDs that the notification was successfully queued to be delivered to.
+++
|===

[[GcmNotification]]
== GcmNotification

++++
 @author Michal Boska
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[collapseKey]]`collapseKey`|`String`|
+++
A collapse key used to deliver multiple notifications of the same kind, of which only the latest is visible to the user.

 See <a href="https://developers.google.com/cloud-messaging/http-server-ref#send-downstream">GCM notification JSON syntax</a>
+++
|[[data]]`data`|`Json object`|
+++
A custom payload that will be available to the application processing this message on the Android device.

 See <a href="https://developers.google.com/cloud-messaging/http-server-ref#send-downstream">GCM notification JSON syntax</a>
+++
|[[delayWhileIdle]]`delayWhileIdle`|`Boolean`|
+++
Only deliver the notification if the target device is active (waked, screen on)

 See <a href="https://developers.google.com/cloud-messaging/http-server-ref#send-downstream">GCM notification JSON syntax</a>
+++
|[[dryRun]]`dryRun`|`Boolean`|-
|[[registrationIds]]`registrationIds`|`Array of String`|-
|[[restrictPackageName]]`restrictPackageName`|`String`|
+++
Only send the notification to an application, whose package name matches this value

 See <a href="https://developers.google.com/cloud-messaging/http-server-ref#send-downstream">GCM notification JSON syntax</a>
+++
|[[ttlSeconds]]`ttlSeconds`|`Number (Long)`|
+++
How long the message should be queued for delivery (at Google Servers) before discarding it as undeliverable, if delivery was not possible until then.

 See <a href="https://developers.google.com/cloud-messaging/http-server-ref#send-downstream">GCM notification JSON syntax</a>
+++
|===

